const songlist = [
  "All Music/Architects/Holy Hell/01 - Architects - ＂Death Is Not Defeat＂.mp3",
  "All Music/Architects/Holy Hell/02 - Architects - ＂Hereafter＂.mp3",
  "All Music/Architects/Holy Hell/03 - Architects - ＂Mortal After All＂ (Full Album Stream).mp3",
  "All Music/Architects/Holy Hell/04 - Architects - ＂Holy Hell＂ (Full Album Stream).mp3",
  "All Music/Architects/Holy Hell/05 - Architects - ＂Damnation＂ (Full Album Stream).mp3",
  "All Music/Architects/Holy Hell/06 - Architects - ＂Royal Beggars＂.mp3",
  "All Music/Architects/Holy Hell/07 - Architects - ＂Modern Misery＂.mp3",
  "All Music/Architects/Holy Hell/08 - Architects - ＂Dying To Heal＂ (Full Album Stream).mp3",
  "All Music/Architects/Holy Hell/09 - Architects - ＂The Seventh Circle＂ (Full Album Stream).mp3",
  "All Music/Architects/Holy Hell/10 - Architects - ＂Doomsday＂.mp3",
  "All Music/Architects/Holy Hell/11 - Architects - ＂A Wasted Hymn＂ (Full Album Stream).mp3",
  "All Music/Architects/Nightmares/1 - To the Death.mp3",
  "All Music/Architects/Nightmares/2 - You Don't Walk Away from Disemberment.mp3",
  "All Music/Architects/Nightmares/3 - Minesweeper.mp3",
  "All Music/Architects/Nightmares/4 - They'll be Hanging Us Tonight.mp3",
  "All Music/Architects/Nightmares/5 - This Confession Means Nothing.mp3",
  "All Music/Architects/Nightmares/6 - In the Desert.mp3",
  "All Music/Architects/Nightmares/7 - A Portrait for the Deceased.mp3",
  "All Music/Architects/Nightmares/8 - The Darkest Tomb.mp3",
  "All Music/Baroness/Blue Album/01 - Bullhead’s Psalm.mp3",
  "All Music/Baroness/Blue Album/02 - The Sweetest Curse.mp3",
  "All Music/Baroness/Blue Album/03 - Jake Leg.mp3",
  "All Music/Baroness/Blue Album/04 - Steel That Sleeps the Eye.mp3",
  "All Music/Baroness/Blue Album/05 - Swollen and Halo.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/01 - THE END.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/02 - TOO LATE.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/03 - BETTER HELL (Thicc boi).mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/04 - EMPTYHANDED.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/05 - MISS ME.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/06 - BOUTTA CASHEW.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/07 - LIVIN' LAUGHIN' LOVIN'.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/08 - SPINNIN' YOU AROUND.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/09 - 2016 CAVALIERS (Ohio).mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/10 - ALL GAS.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/11 - BLINDSIDED.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/12 - STRAIGHT THROUGH YOU.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/13 - TALKIN' 2 UR GHOST.mp3",
  "All Music/Bilmuri/AMERICAN MOTOR SPORTS/14 - DRUNK ENOUGH.mp3"
];
